# Generated by Django 5.2.5 on 2025-08-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='changeme123', max_length=128),
        ),
    ]
